package com.example.giftquest.ui.screens
/**
 * Random teaser messages shown on partner's gift cards.
 * Inspired by Minecraft splash texts — picked randomly per item.
 * The item index is used as seed so the same item always shows the same text.
 */
object GiftSplashTexts {

    private val texts = listOf(
        "Something your partner has been dreaming about... 🌙",
        "A surprise waiting to happen 🎁",
        "Worth every penny of the guessing 💭",
        "Your partner's eyes lit up when they found this ✨",
        "This one took them a while to decide on 🤔",
        "Hidden in plain sight... or is it? 🕵️",
        "A little mystery never hurt anyone 😏",
        "Can you crack the code? 🔍",
        "Your partner really wants this one 💝",
        "The perfect gift... if you can guess it 🎯",
        "Some things are worth the wait 🌟",
        "A wish wrapped in mystery 🎀",
        "Think you know your partner? Prove it! 😄",
        "This one has a story behind it 📖",
        "Your partner smiled adding this 😊",
        "Not too expensive, not too cheap... maybe 🤷",
        "A clue: it exists. Good luck! 🍀",
        "Somewhere between obvious and impossible 🧩",
        "Your partner's heart is set on this 💕",
        "Every guess brings you closer... or not 😅",
        "The mystery deepens... 🌌",
        "Plot twist incoming 🎬",
        "Your partner's secret wish 🤫",
        "This one made them smile 😌",
        "A gift that speaks volumes 📢",
        "The suspense is killing me! 😱",
        "Your partner's been hinting at this 🗣️",
        "Wrapped in hope and wonder 💫",
        "The answer is somewhere in here... 🔮",
        "Your partner's dream come true ✨",
        "Is it what you think it is? 🤨",
        "A treasure worth seeking 💎",
        "Your partner circled this in the catalog 📑",
        "Something that makes them tick ⏰",
        "The gift that keeps on giving 🎊",
        "Your partner's bucket list item 📋",
        "More valuable than gold 🏆",
        "A piece of their happiness 🧩",
        "Your partner's eyes will pop 👀",
        "The mystery box opens here 📦",
        "Your partner deserves this 👑",
        "A moment they've been waiting for ⏳",
        "The best guess wins! 🏅",
        "Your partner's favorite things combined 🎯",
        "Something whispered about in dreams 💤",
        "The gift that says 'I know you' 💕",
        "Your partner's hidden passion 🔥",
        "A wish upon a star ⭐",
        "The perfect timing for this 🕐",
        "Your partner's smile is guaranteed 😁",
        "A secret sealed with joy 🔐",
        "The answer lies within 🎭",
        "Your partner's been dropping hints 💡",
        "Something to celebrate 🎉",
        "The gift of understanding 🧠",
        "Your partner's next adventure 🗺️",
        "A moment frozen in time 📸",
        "The clue is in the details 🔍",
        "Your partner's been patient 😌",
        "Something that brings them peace ☮️",
        "The gift that fits just right 👌",
        "Your partner's lucky number 7️⃣",
        "A treasure map leads here 🗺️",
        "The mystery unfolds slowly 📖",
        "Your partner's been dreaming of this 🌙",
        "Something between a and z 🔤",
        "The gift code is cracking 🔓",
        "Your partner's next obsession 🤩",
        "A moment to cherish forever 💞",
        "The answer is in your heart 💖",
        "Your partner's deserves the best 🌟",
        "Something that sparks joy 🌺",
        "The gift wraps up perfectly 📦",
        "Your partner's been saving room for this 🏠",
        "A clue hidden in plain sight 👁️",
        "The mystery grows thicker 🌫️",
        "Your partner's perfect match 💑",
        "Something that never goes out of style ✨",
        "The gift keeps the mystery alive 🎪",
        "Your partner's been marking days 📅",
        "A treasure in the rough 💎",
        "The answer awaits your guess 🎲",
        "Your partner's kindred spirit 👫",
        "Something that feels like home 🏡",
        "The gift of laughter 😂",
        "Your partner's secret stash location 🗂️",
        "A moment of pure magic 🪄",
        "The clue whispers softly 🤫",
        "Your partner's been counting down 🔢",
        "Something that defies expectation 🤯",
        "The gift speaks their language 🗣️",
        "Your partner's heart desires this 💘",
        "A treasure worth more than words 🏆",
        "The mystery is half the fun 🎨",
        "Your partner's been dropping breadcrumbs 🍞",
        "Something that brings out their glow ✨",
        "The gift of happiness 😊",
        "Your partner's next chapter 📚",
        "A clue in every shadow 🌑",
        "The answer dances just out of reach 💃",
        "Your partner's been manifesting this 🌠",
        "Something wrapped in starlight 🌃",
        "The gift that bonds you closer 🤝",
        "Your partner's secret love language 💬",
        "A treasure that's uniquely theirs 🎁",
        "The mystery calls to something deep 🌊",
        "Your partner's been leaving notes 📝",
        "Something that makes time stop ⏹️",
        "The gift of understanding them 🔍",
        "Your partner's dream fuel 🚀",
        "A moment that changes everything 🌈",
        "The clue is written in their smile 😊",
        "Your partner's been window shopping 🛍️",
        "Something that feels like destiny ✨",
        "The gift writes its own story 📖",
        "Your partner's North Star ⭐",
        "A treasure map to their joy 🗺️",
        "The mystery deepens with each glance 👀",
        "Your partner's been praying for this 🙏",
        "Something that sparks recognition 💫",
        "The gift that proves your love 💕",
        "Your partner's been holding back tears 😢",
        "A clue in the reflection 🪞",
        "The answer lives in their eyes 👁️",
        "Your partner's secret wish list 📋",
        "Something that feels inevitable 🎯",
        "The gift of shared dreams 🌙",
        "Your partner's been rehearsing their reaction 🎭",
        "A treasure that glows from within 💡",
        "The mystery embraces the unknown 🌌",
        "Your partner's been making space 📦",
        "Something that smells like home 🏠",
        "The gift that speaks to their soul 🎵",
        "Your partner's been leaving hints everywhere 🗺️",
        "A moment suspended in time ⏰",
        "The clue floats on the breeze 🌬️",
        "Your partner's been saving this spot 💺",
        "Something that feels like a sign 🪧",
        "The gift of becoming whole 💯",
        "Your partner's next great love 💕",
        "A treasure chest of memories 🎬",
        "The mystery unfolds like petals 🌹",
        "Your partner's been lighting candles 🕯️",
        "Something that answers their prayer 🙏",
        "The gift that heals the heart 💗",
        "Your partner's been wishing upon stars ⭐",
        "A clue written in the stars 🌟",
        "The answer whispers your name 👂",
        "Your partner's treasure is waiting 💰",
        "Something that makes them whole 🧩",
        "The gift of infinite possibilities ∞",
        "Your partner's been practicing gratitude 🙌",
        "A moment that feels like coming home 🏡",
        "The mystery blooms in spring 🌸",
        "Your partner's been keeping the faith ✨",
        "Something that tastes like victory 🏆",
        "The gift that echoes through time ⏳",
        "Your partner's been making wishes 🌠",
        "A treasure that never tarnishes 👑",
        "The clue hides in plain sight again 🔍",
        "Your partner's answer to prayers 🙏",
        "Something that feels like flying 🕊️",
        "The gift of boundless joy 🎪",
        "Your partner's been counting blessings 🙌",
        "A moment of pure connection 🤝",
        "The mystery calls like a siren 🧜‍♀️",
        "Your partner's been manifesting magic 🪄",
        "Something that shimmers and shines ✨",
        "The gift that binds forever 💍",
        "Your partner's holy grail awaits 🏆",
        "A treasure wrapped in rainbow light 🌈",
        "The clue dances in moonlight 🌙",
        "Your partner's dreams incarnate 💭",
        "Something that resonates deeply 🔊",
        "The gift of eternal youth 🧴",
        "Your partner's been saving up hope 💝",
        "A moment of revolutionary change 🔄",
        "The mystery perfumes the air 🌸",
        "Your partner's secret garden blooms 🌻",
        "Something that defies time 🕰️",
        "The gift that feeds the soul 🍽️",
        "Your partner's been holding their breath 😮",
        "A clue in every heartbeat 💓",
        "The answer sings your name 🎵",
        "Your partner's paradise found 🏝️",
        "Something that feels like lightning ⚡",
        "The gift of second chances 🔄",
        "Your partner's been crossing days off 📅",
        "A treasure that multiplies joy 📈",
        "The mystery wraps around the heart 🎀",
        "Your partner's been sending signals 📡",
        "Something that elevates the spirit 🕯️",
        "The gift that makes life complete 🎬",
        "Your partner's been writing destiny 📝",
        "A moment that defines forever 👰",
        "The clue floats like a feather 🪶",
        "Your partner's answer to longing 💕",
        "Something that blooms eternal 🌺",
        "The gift of understanding love 💖",
        "Your partner's been chasing rainbows 🌈",
        "A treasure beyond measure 📏",
        "The mystery lives in the silence 🤐",
        "Your partner's beacon shines here 💡",
        "Something that tastes like magic 🪄",
        "The gift that never disappoints 🎁",
        "Your partner's been holding the line 📞",
        "A clue in the quantum foam ⚛️",
        "The answer crystallizes here 💎",
        "Your partner's pot of gold 🌈",
        "Something that feels like destiny's call 📞",
        "The gift of knowing them fully 🧠",
        "Your partner's been rehearsing 🎬",
        "A moment of absolute clarity 🔦",
        "The mystery breathes with life 🌬️",
        "Your partner's been building anticipation 🏗️",
        "Something that shines eternally ⭐",
        "The gift that seals your bond 🔐",
        "Your partner's been keeping secrets 🤐",
        "A treasure that appreciates over time 📈",
        "The clue hides in the obvious 🙈",
        "Your partner's greatest desire 🎯",
        "Something that sparks recognition instantly 💫",
        "The gift of perfect timing ⏱️",
        "Your partner's been faithful and true 💕",
        "A moment of quantum entanglement 🔗",
        "The mystery deepens with knowing 🔍",
        "Your partner's North Star shines bright ⭐",
        "Something that feels like coming alive 🌱",
        "The gift that speaks volumes softly 🤫",
        "Your partner's been sowing seeds 🌾",
        "A clue written across the sky 🌅",
        "The answer blooms like roses 🌹",
        "Your partner's paradise awaits here 🏖️",
        "Something that makes the heart race 💨",
        "The gift of infinite wonder 🌌",
        "Your partner's been counting stars 🌠",
        "A treasure wrapped in eternal love 💞",
        "The mystery whispers ancient secrets 📜",
        "Your partner's beacon still shines 💡",
        "Something that feels revolutionary ⚙️",
        "The gift that transcends time ⏳",
        "Your partner's been holding dreams 💤",
        "A moment of pure transcendence ✨",
        "The clue sings an ancient song 🎶",
        "Your partner's answer appears here 🔮",
        "Something that makes them levitate 🎈",
        "The gift of eternal springtime 🌸",
        "Your partner's been manifesting madly 🎊",
        "A treasure that shines like dawn 🌅",
        "The mystery calls like destiny 📞",
        "Your partner's secret passion burns 🔥",
        "Something that transcends the ordinary 🌟",
        "The gift that proves devotion 💍",
        "Your partner's been awaiting this moment ⏰",
        "A clue in the dance of light ✨",
        "The answer lives within love 💕",
        "Your partner's treasure room opens 🚪",
        "Something that feels like homecoming 🏠",
        "The gift of knowing their soul 👻",
        "Your partner's been losing sleep 😴",
        "A moment of beautiful recognition 🤩",
        "The mystery embraces possibility 🌈",
        "Your partner's been sending love signals 📡",
        "Something that defies explanation ❓",
        "The gift that heals all wounds 🩹",
        "Your partner's been crossing fingers 🤞",
        "A treasure that's truly priceless 💎",
        "The clue dances in shadow and light 🌓",
        "Your partner's answer awaits always 🔔",
        "Something that feels like magic awakening 🪄",
        "The gift of understanding their language 🗣️",
        "Your partner's been drawing this picture 🎨",
        "A moment of perfect alignment 🎯",
        "The mystery sings with knowing 🎵",
        "Your partner's secret sanctuary here 🕌",
        "Something that sparkles with promise ✨",
        "The gift that binds souls together 🔗",
        "Your partner's been planting gardens 🌳",
        "A clue hidden in their laughter 😄",
        "The answer echoes through eternity ∞",
        "Your partner's paradise in a box 📦",
        "Something that feels like flying home 🏠",
        "The gift of becoming legendary 👑",
        "Your partner's been writing love letters 💌",
        "A treasure map to their heart 💖",
        "The mystery unfolds with grace 🎭",
        "Your partner's lighthouse stands tall 🗼",
        "Something that tastes like victory 🏆",
        "The gift that echoes forever 🔊",
        "Your partner's been holding back joy 😊",
        "A moment of absolute belonging 🤗",
        "The clue floats on sunset clouds 🌅",
        "Your partner's greatest wish here 🌟",
        "Something that makes them invincible 💪",
        "The gift of loving them wisely 💝",
        "Your partner's been dreaming in color 🎨",
        "A treasure beyond all treasures 👑",
        "The mystery calls to their spirit 👻",
        "Your partner's secret name's in here 🏷️",
        "Something that feels like evolution 🧬",
        "The gift that transcends all limits ∞",
        "Your partner's been holding out hope 🙏",
        "A clue in the space between heartbeats 💗",
        "The answer shines with inner light 💫",
        "Your partner's garden grows wild here 🌿",
        "Something that sparkles eternal ⭐",
        "The gift of knowing devotion 💕",
        "Your partner's been saving this spot 🎪",
        "A moment frozen in love's amber 🍯",
        "The mystery breathes with wonder 🌬️",
        "Your partner's been manifesting daily 🙏",
        "Something that feels like lightning struck ⚡",
        "The gift that redefines forever 👰",
        "Your partner's been counting blessings 🙌",
        "A treasure that multiplies infinitely 📈",
        "The clue sings in morning light 🌄",
        "Your partner's answer crystallizes 💎",
        "Something that makes their pulse quicken 💓",
        "The gift of eternal recognition 🎯",
        "Your partner's been holding fast 🤝",
        "A moment of revolutionary love 💕",
        "The mystery embraces the sacred 🕯️",
        "Your partner's secret kingdom revealed 👑",
        "Something that defies all logic ❓",
        "The gift that seals the deal 🤝",
        "Your partner's been paying attention 👀",
        "A clue in the quantum entanglement 🔗",
        "The answer lives in their bloodline 🩸",
        "Your partner's paradise opens 🚪",
        "Something that feels like coming home 🏡",
        "The gift of infinite gratitude 🙏",
        "Your partner's been marking the calendar 📅",
        "A treasure that transcends time ⏳",
        "The mystery speaks in riddles 🧩",
        "Your partner's beacon burns bright 🔥",
        "Something that sparkles with destiny ✨",
        "The gift that proves your love 💞",
        "Your partner's been rehearsing joy 😊",
        "A moment of absolute certainty ✔️",
        "The clue hides in reflection 🪞",
        "Your partner's greatest joy awaits 🎉",
        "Something that makes them immortal 👑",
        "The gift of understanding devotion 💕",
        "Your partner's been holding the vision 👀",
        "A treasure wrapped in stardust ⭐",
        "The mystery deepens into knowing 🔍",
        "Your partner's secret door opens 🔓",
        "Something that feels like destiny 🎯",
        "The gift that changes everything 🔄",
        "Your partner's been crossing items 📝",
        "A clue dancing on the breeze 🌬️",
        "The answer blooms in spring ⚘",
        "Your partner's pot of gold waits 🌈",
        "Something that shines like diamonds 💎",
        "The gift of perfect synchronicity 🔄",
        "Your partner's been faithful always 💕",
        "A moment of quantum possibility 🌌",
        "The mystery calls like sirens 🧜",
        "Your partner's lighthouse guides home 🗼",
        "Something that transcends understanding 🌟",
        "The gift that never fades 🌺",
        "Your partner's been sowing love 💕",
        "A treasure beyond imagination 🎨",
        "The clue floats in cosmic dust ⭐",
        "Your partner's answer resonates 🔊",
        "Something that makes them complete 🧩",
        "The gift of eternal bond 🔐",
        "Your partner's been keeping vigil 🕯️",
        "A moment of beautiful synchronicity 🎵",
        "The mystery unfolds like destiny 📖",
        "Your partner's secret garden blooms 🌸",
        "Something that sparkles timelessly ✨",
        "The gift that defines your love 💝",
        "Your partner's been holding faith 🙏",
        "A clue in the still of night 🌙",
        "The answer awakens within 💫",
        "Your partner's paradise manifest 🏝️",
        "Something that feels like lightning ⚡",
        "The gift of knowing them fully 🧠",
        "Your partner's been manifesting magic 🪄",
        "A treasure that's forever blessed 🙏",
        "The mystery sings ancient songs 🎵",
        "Your partner's beacon never dims 💡",
        "Something that tastes like dreams 💭",
        "The gift that echoes through ages ⏳",
        "Your partner's been counting moments ⏰",
        "A moment of pure awakening 🌅",
        "The clue dances in starlight 🌟",
        "Your partner's greatest desire blooms 🌹",
        "Something that makes them fly 🕊️",
        "The gift of endless possibility ∞",
        "Your partner's been sowing seeds 🌱",
        "A treasure that appreciates daily 📈",
        "The mystery reveals the sacred 🕯️",
        "Your partner's secret love lives here 💕",
        "Something that transcends the mortal 👑",
        "The gift that binds eternally 💍",
        "Your partner's been holding dreams 💤",
        "A clue written in morning dew 🌧️",
        "The answer crystallizes perfectly 💎",
        "Your partner's paradise is here 🏖️",
        "Something that sparkles endlessly ⭐",
        "The gift of understanding souls 👻",
        "Your partner's been crossing days 📅",
        "A moment of revolutionary discovery 🔍",
        "The mystery breathes with life 🌬️",
        "Your partner's secret kingdom awaits 👑",
        "Something that defies all odds 🎲",
        "The gift that seals your fate 🔐",
        "Your partner's been manifesting true 🎯",
        "A treasure beyond all measure 📏",
        "The clue hides where love lives 💕",
        "Your partner's answer sings clear 🎵",
        "Something that makes time stop ⏱️",
        "The gift of knowing their essence 🌟",
        "Your partner's been patient always 😌",
        "A moment of absolute clarity 🔦",
        "The mystery embraces the infinite ∞",
        "Your partner's beacon shines eternal 💡",
        "Something that feels like magic ✨",
        "The gift that never disappoints 🏆",
        "Your partner's been holding you close 🤗",
        "A clue in the quantum foam ⚛️",
        "The answer lives in devotion 💕",
        "Your partner's paradise found 🌈",
        "Something that transcends all limits ∞",
        "The gift of infinite love 💞",
        "Your partner's been writing fate 📝",
        "A treasure that multiplies joy 🎊",
        "The mystery deepens with wonder 🌌",
        "Your partner's secret sanctuary 🕌",
        "Something that sparkles forever ⭐",
        "The gift that proves all 💝",
        "Your partner's been holding strong 💪",
        "A moment of perfect alignment 🎯",
        "The clue sings in perfect harmony 🎶",
        "Your partner's greatest wish blooms 🌹",
        "Something that makes them soar 🚀",
        "The gift of eternal recognition 👑",
        "Your partner's been manifesting here 🙏",
        "A treasure beyond all knowledge 📚",
        "The mystery calls to destiny 📞",
        "Your partner's lighthouse glows 🗼",
        "Something that defies comprehension ❓",
        "The gift that changes souls 👻",
        "Your partner's been crossing moments ⏰",
        "A clue floating on moon beams 🌙",
        "The answer awakens the heart 💓",
        "Your partner's paradise manifest 🏝️",
        "Something that feels like coming home 🏠",
        "The gift of knowing love deeply 💕",
        "Your partner's been holding fast 🤝",
        "A moment of revolutionary change 🔄",
        "The mystery embraces eternity ∞",
        "Your partner's secret desire blooms 🌸",
        "Something that sparkles with truth ✨",
        "The gift that binds forever 💍",
        "Your partner's been dreaming awake 👀",
        "A treasure wrapped in rainbows 🌈",
        "The clue hides in plain wonder 😲",
        "Your partner's answer resonates deep 🔊",
        "Something that makes their heart race 💗",
        "The gift of perfect devotion 💕",
        "Your partner's been planting love 💕",
        "A moment of absolute belonging 🤗",
        "The mystery sings eternal songs 🎵",
        "Your partner's beacon still burns 🔥",
        "Something that transcends the mundane 🌟",
        "The gift that defines everything 💝",
        "Your partner's been holding the light 💡",
        "A clue dancing on butterfly wings 🦋",
        "The answer blooms in their soul 🌺",
        "Your partner's paradise opens wide 🚪",
        "Something that feels like evolution 🧬",
        "The gift of knowing all 🧠",
        "Your partner's been crossing rivers 🌊",
        "A treasure that multiplies infinitely 📈",
        "The mystery deepens into love 💕",
        "Your partner's secret garden grows 🌿",
        "Something that sparkles with destiny ✨",
        "The gift that never ends 🔄",
        "Your partner's been manifesting power 💪",
        "A moment of perfect synchronicity 🎵",
        "The clue floats in stardust ⭐",
        "Your partner's greatest love awaits 💕",
        "Something that makes them legendary 👑",
        "The gift of understanding all 💭",
        "Your partner's been holding vigil 🕯️",
        "A treasure beyond all precious things 💎",
        "The mystery reveals the divine 👼",
        "Your partner's lighthouse eternal 🗼",
        "Something that transcends existence ∞",
        "The gift that seals your souls 🔐",
        "Your partner's been faithful true 💕",
        "A clue in the cosmic connection 🌌",
        "The answer lives in forever 👰",
        "Your partner's paradise eternal 🏝️",
        "Something that shines like hope 💡",
        "The gift of infinite recognition 🎯",
        "Your partner's been marking time ⏰",
        "A moment of revolutionary love 💕",
        "The mystery calls eternally 📞",
        "Your partner's secret door awaits 🚪",
        "Something that defies all reason 🤯",
        "The gift that proves devotion 💍",
        "Your partner's been sowing gold 💰",
        "A treasure that never diminishes 📈",
        "The clue sings in all languages 🗣️",
        "Your partner's answer crystallizes 💎",
        "Something that makes eternity brief ⏳",
        "The gift of knowing their truth 💭",
        "Your partner's been holding dreams 💤",
        "A moment of absolute transcendence ✨",
        "The mystery deepens with grace 🎭",
        "Your partner's beacon never fails 💡",
        "Something that sparkles infinite ⭐",
        "The gift that changes fate 🔄",
        "Your partner's been manifesting true 🙏",
        "A clue hidden in eternity ∞",
        "The answer blooms eternal 🌹",
        "Your partner's paradise opens now 🚪",
        "Something that feels like destiny 🎯",
        "The gift of complete knowing 🧠",
        "Your partner's been crossing thresholds 🚪",
        "A treasure that's eternally blessed 🙏",
        "The mystery speaks in hearts 💕",
        "Your partner's secret name glows 💡",
        "Something that transcends all time ⏳",
        "The gift that never fades away 🌺",
        "Your partner's been holding forever 👰",
        "A moment of quantum entanglement 🔗",
        "The clue dances in infinite ways 💃",
        "Your partner's greatest joy waits 🎉",
        "Something that makes them infinite ∞",
        "The gift of eternal understanding 💭",
        "Your partner's been sowing wonder 😲",
        "A treasure wrapped in pure love 💕",
        "The mystery reveals all truth 💯",
        "Your partner's lighthouse burns bright 🔥",
        "Something that sparkles with souls ✨",
        "The gift that binds all hearts 💖",
        "Your partner's been crossing mountains 🏔️",
        "A clue in the eternal dance 💃",
        "The answer sings in all notes 🎵",
        "Your partner's paradise waits now 🏖️",
        "Something that feels like lightning ⚡",
        "The gift of knowing everything 🧠",
        "Your partner's been holding light 💡",
        "A moment of absolute certainty ✔️",
        "The mystery embraces the absolute ∞",
        "Your partner's secret garden wild 🌿",
        "Something that defies all odds 🎲",
        "The gift that changes all things 🔄",
        "Your partner's been manifesting always 🙏",
        "A treasure beyond all universe 🌌",
        "The clue floats on cosmic winds 🌬️",
        "Your partner's answer glows eternal 💫",
        "Something that makes them divine 👼",
        "The gift of infinite possibility ∞",
        "Your partner's been crossing oceans 🌊",
        "A moment of pure enlightenment 💡",
        "The mystery sings in all keys 🎵",
        "Your partner's beacon eternal flame 🔥",
        "Something that transcends the universe 🌌",
        "The gift that proves eternal love 💕",
        "Your partner's been holding always 👰",
        "A clue in the fabric of fate 🧵",
        "The answer blooms in infinity ∞",
        "Your partner's paradise eternal bliss 🏝️",
        "Something that sparkles like stars ⭐"
    )

    fun getFor(itemId: String): String {
        val index = Math.abs(itemId.hashCode()) % texts.size
        return texts[index]
    }
}